# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yKVY9vD7uwuuriPrH7zRJtjHD3LYTiz
"""

print("abc")