# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cByR7ZmE7PhJos_R9MTHUmENWY7r-Tb5
"""

a,b=10,20
print(a+b)