# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzA181M0eCoSVPCqYu_5gk5VXd1Q9csC
"""

n=7
print(n*n)